# tomcat配置
server:
  port: 8088 # 服务端口

# springboot配置
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: v-blog # 服务名称
  profiles:
    active: dev # 激活环境
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 数据库连接池
    url: jdbc:mysql:///${mysql.database}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${mysql.username}
    password: ${mysql.password}

# mybatis-plus配置
mybatis-plus:
  type-aliases-package: org.sang.pojo.po # 扫描实体类
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台日志打印sql
  global-config:
    db-config:
      id-type: auto # 全局主键策略:自增长

# 日志配置
logging:
  level:
    org.springframework.security: info # 记录spring security的日志
